version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Def12345
      POSTGRES_USER: groupy
      POSTGRES_DB: groupy
    ports:
      - 5432:5432
  openldap:
    image: docker.io/bitnami/openldap:2-debian-10
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2